# ---------- BUILDER STAGE ----------
# Usa uma imagem Node para compilar o projeto
FROM node:22-alpine AS builder

WORKDIR /app

# Copia apenas os arquivos de dependência primeiro (para cache do Docker)
COPY /front/package*.json ./

# Instala as dependências (npm ci é mais rápido e seguro para builds do que npm install)
RUN npm ci
# Instala dependências (usando install em vez de ci)
#RUN npm install

# Copia o código fonte do projeto
COPY /front .

# Gera o build de produção
# O resultado ficará geralmente em /app/dist/nome-do-seu-projeto
RUN npm run build -- --configuration production

# ---------- FINAL IMAGE ----------
# Usa Nginx para servir os arquivos estáticos (muito mais leve e performático que Node)
FROM nginx:alpine

# Remove a página padrão do Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia o Nginx config customizado (veja abaixo porque isso é essencial)
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copia os arquivos compilados do estágio builder para a pasta do Nginx
COPY --from=builder /app/dist/front/browser /usr/share/nginx/html

EXPOSE 80

# O Nginx roda em foreground por padrão na imagem Alpine
CMD ["nginx", "-g", "daemon off;"]